name: test
on: [push]

jobs:

  test:
    name: run-tests
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install Dependencies
        run: bun i

      - run: bun test
